[package]
name = "rphira-mp"
version = "0.0.1"
edition = "2024"
description = "Phira multiplayer server"

[lib]
name = "phira_mp"
path = "src/lib.rs"

[[bin]]
name = "phira-mp"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8"
bytes = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time = { version = "0.3", features = ["local-offset"] }
clap = { version = "4", features = ["derive"] }
lru = "0.12"
futures = "0.3"
zstd = "0.13"
terminal-console = { path = "terminal-console" }
fluent = "0.17.0"
fluent-syntax = "0.12.0"
unic-langid = "0.9"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
